version: 2.1

executors:
  default:
    working_directory: ~/workspace
    docker:
      - image: circleci/node
    environment:
      TZ: /usr/share/zoneinfo/Asia/Tokyo

commands:
  attach:
    steps:
      - attach_workspace:
          at: .
  persist:
    steps:
      - persist_to_workspace:
          root: .
          paths:
            - "*"
  ssh_keys:
    steps:
      - add_ssh_keys:
          fingerprints:
            - "19:c1:f4:85:71:70:19:cb:0a:09:70:03:ad:4b:08:22"

jobs:
  setup:
    executor: default
    steps:
      - run:
          name: System information
          command: |
            echo "Node $(node -v)"
            echo "Yarn v$(yarn -v)"
      - checkout
      - restore_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Setup
          command: |
            yarn setup
      - save_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - persist
  build:
    executor: default
    steps:
      - attach
      - run:
          name: Build
          command: |
            yarn build
      - store_artifacts:
          path: dist
      - persist
  deploy:
    executor: default
    steps:
      - attach
      - ssh_keys
      - deploy:
          command: |
            ssh-keyscan github.com >> ~/.ssh/known_hosts
            yarn deploy -u "`git --no-pager show -s --format='%cn <%ce>' HEAD`"


workflows:
  build-deploy-flow:
    jobs:
      - setup
      - build:
          requires:
            - setup
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: source
